---
# tasks file for enable-vino

- name: vino enable remote access.
  dconf:
    key: '/org/gnome/desktop/remote-access/enabled'
    value: 'true'

- name: vino disable prompt
  dconf:
    key: '/org/gnome/desktop/remote-access/prompt-enabled'
    value: 'false'    

- name: vino /org/gnome/desktop/remote-access/require-encryption
  dconf:
    key: '/org/gnome/desktop/remote-access/require-encryption'
    value: 'false'        
    